force-app/main/default/objects/Custom_Report__mdt/Custom_Report__mdt.object-meta.xml
<CustomObject>
    <label>Custom Report</label>
    <pluralLabel>Custom Reports</pluralLabel>
</CustomObject>

force-app/main/default/objects/Custom_Report__mdt/fields/Chunks_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Chunks_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chunks Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Report__mdt/fields/Index_Field_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Index_Field_Api_Name__c</fullName>
    <label>Index Field Api Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

excelExport/force-app/main/default/objects/Custom_Report__mdt/fields/SObject_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Api_Name__c</fullName>
    <label>SObject Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Report_Field__mdt/Custom_Report_Field__mdt.object-meta.xml
<CustomObject>
    <label>Custom Report Field</label>
    <pluralLabel>Custom Report Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Custom_Report_Field__mdt/fields/Custom_Report__c.field-meta.xml
<CustomField>
    <fullName>Custom_Report__c</fullName>
    <label>Custom Report</label>
    <referenceTo>Custom_Report__mdt</referenceTo>
    <relationshipLabel>Custom Report Fields</relationshipLabel>
    <relationshipName>Custom_Report_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

excelExport/force-app/main/default/classes/CustomReportsController.cls
public with sharing class CustomReportsController {
   @AuraEnabled
   public static String generateReportData(String reportToGenerate, String lastValueFromPagination){
    if(String.isEmpty(reportToGenerate)) return null;

   try {
        List<Map<String, Object>> result = new CustomReportsService()
            .setReportToGenerate(reportToGenerate)
            .setLastValueFromPagination(lastValueFromPagination)
            .fetchData()
            .toListOfMap();
        return JSON.serialize(result);
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
   }

   @AuraEnabled
public static List<Map<String, String>> getActiveReportOptionList() {
    List<Map<String, String>> reportOptions = new List<Map<String, String>>();
    try {
        List<Custom_Report__mdt> reports = new CustomReportsService().fetchReports();
        for (Custom_Report__mdt r : reports) {
            Map<String, String> reportOption = new Map<String, String>();
            reportOption.put('label', r.MasterLabel);
            reportOption.put('value', r.DeveloperName);
            reportOptions.add(reportOption);
        }
    } catch (Exception e) {
        throw new AuraHandledException('Failed to fetch active reports: ' + e.getMessage());
    }
    return reportOptions;
}

@AuraEnabled
public static Map<String, Object> getActiveReportConfig(){
    Map<String, Object> reportConfigList = new Map<String,Object>();
    try {
        CustomReportsService service = new CustomReportsService();
        List<Custom_Report__mdt> reports = service.fetchReports();
        for (Custom_Report__mdt r : reports) {
            Map<String, Object> reportConfig = new Map<String, Object>();
            SObjectType targetSObjectType = ((SObject) Type.forName(r.SObject_Api_Name__c).newInstance()).getSObjectType();
            List<Custom_Report_Field__mdt> fieldsToGetTheLabelsFor = r.Custom_Report_Fields__r;
            Map<String, String> fieldsLabel = service.getFieldsLabel(targetSObjectType, fieldsToGetTheLabelsFor, null);
            reportConfig.put('IndexFieldLabel', fieldsLabel.get(r.Index_Field_Api_Name__c));
            reportConfig.put('ChunksEnabled', r.Chunks_Enabled__c);
            reportConfigList.put(r.DeveloperName, reportConfig);
        }
    } catch (Exception e) {
        throw new AuraHandledException('Failed to fetch active reports config: ' + e.getMessage());
    }
    return reportConfigList;
}

}